apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: serverless-operator-136-fbc-418
spec:
  description: serverless-operator release-1.36 FBC 4.18
  displayName: serverless-operator release-1.36 FBC 4.18
