name: 'Setup Go'
description: |
  Shared Golang setup to maitain same version across actions

inputs:
  go-version:
    description: |
      Override default Go version

    required: false

runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version || '1.22' }}
