apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../docker-build.yaml
patches:
  - path: ../patch_additional_tags.patch.yaml
    target:
      name: docker-build
  - path: ../patch_prefetch-input_dev-package-managers.patch.yaml
    target:
      name: docker-build
  - path: ../patch_source_image.patch.yaml
    target:
      name: docker-build
openapi:
  path: ../pipeline_schema.json
