apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
  name: serverless-metadata-webhook-136
spec:
  componentName: serverless-metadata-webhook-136
  application: serverless-operator-136
   
  source:
    git:
      url: https://github.com/openshift-knative/serverless-operator.git
      context: 
      dockerfileUrl: serving/metadata-webhook/Dockerfile
      revision: main
