apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-build
spec:
  params:
    - name: build-image-index
      default: "false"
  tasks:
    - name: build-images
      params:
        - name: IMAGE_APPEND_PLATFORM
          value: "false"
