apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-build
spec:
  tasks:
    # Remove clair-scan task from upstream
    - $patch: delete
      name: clair-scan
    # Add roxctl-scan task
    - name: roxctl-scan
      matrix:
        params:
          - name: image-platform
            value:
              - $(params.build-platforms)
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: roxctl-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-roxctl-scan:0.1@sha256:97e2b2cdca9110fdc8a93ba585a1a1a743f989f2fd85f4073f6e5ea9ad2ce828
          - name: kind
            value: task
        resolver: bundles
      timeout: 20m
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
