apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/releasePlanAdmission: 'serverless-operator-136-1350-fbc-stage'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: serverless-operator-136-fbc-414-1350-stage
spec:
  releaseNotes:
    type: "Product Enhancement Advisory"
    synopsis: "Red Hat OpenShift Serverless Release"
    topic: |
      The 1.35.0 GA release of Red Hat OpenShift Serverless Operator.
      For more details see [product documentation](https://docs.redhat.com/documentation/red_hat_openshift_serverless).
    description: "The 1.35.0 release of Red Hat OpenShift Serverless Operator."
    solution: |
      The Red Hat OpenShift Serverless Operator provides a collection of APIs that
      enables containers, microservices and functions to run "serverless".
      Serverless applications can scale up and down (to zero) on demand and be triggered by a
      number of event sources. OpenShift Serverless integrates with a number of
      platform services, such as Monitoring and it is based on the open
      source project Knative.
    references:
      - "https://docs.redhat.com/documentation/red_hat_openshift_serverless/"
  application: serverless-operator-136-fbc-414
  target: rhtap-releng-tenant
