apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ocp-serverless-tenant
  name: gh-action-runner
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications
  - components
  - imagerepositories
  - integrationtestscenarios
  - releaseplans
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
