---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    pp.engineering.redhat.com/business-unit: hybrid-platforms
  name: serverless-operator-136-1360-fbc-stage
  namespace: rhtap-releng-tenant
spec:
  applications:
    - serverless-operator-136-fbc-414
    - serverless-operator-136-fbc-415
    - serverless-operator-136-fbc-416
    - serverless-operator-136-fbc-417
    - serverless-operator-136-fbc-418
  origin: ocp-serverless-tenant
  policy: fbc-stage
  data:
    releaseNotes:
      product_id: [579]
      product_name: "OpenShift Serverless"
      product_version: "1.36.0"
      references:
        - "https://docs.redhat.com/documentation/red_hat_openshift_serverless/"
      type: "RHEA"
      solution: |
        The Red Hat OpenShift Serverless Operator provides a collection of APIs that
        enables containers, microservices and functions to run "serverless".
        Serverless applications can scale up and down (to zero) on demand and be triggered by a
        number of event sources. OpenShift Serverless integrates with a number of
        platform services, such as Monitoring and it is based on the open
        source project Knative.
      description: "The 1.36.0 release of Red Hat OpenShift Serverless Operator."
      topic: |
        The 1.36.0 GA release of Red Hat OpenShift Serverless Operator.
        For more details see [product documentation](https://docs.redhat.com/documentation/red_hat_openshift_serverless).
      synopsis: "Red Hat OpenShift Serverless Release 1.36.0"
    fbc:
      stagedIndex: true
      fromIndex: "registry-proxy.engineering.redhat.com/rh-osbs/iib-pub-pending:{{ OCP_VERSION }}"
      targetIndex: ""
      publishingCredentials: "staged-index-fbc-publishing-credentials"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      allowedPackages: [serverless-operator]
    sign:
      configMapName: hacbs-signing-pipeline-config-staging-redhatrelease2
      cosignSecretName: konflux-cosign-signing-stage
    intention: staging
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/managed/fbc-release/fbc-release.yaml"
    serviceAccountName: release-index-image-staging
    timeouts:
      pipeline: "4h0m0s"
      tasks: "4h0m0s"
