---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    pp.engineering.redhat.com/business-unit: hybrid-platforms
  name: serverless-operator-135-1350-stage
  namespace: rhtap-releng-tenant
spec:
  applications: [serverless-operator-135]
  origin: ocp-serverless-tenant
  policy: registry-standard-stage
  data:
    releaseNotes:
      product_id: 579
      product_name: "OpenShift Serverless"
      product_version: "1.35.0"
      references:
        - https://docs.redhat.com/en/documentation/red_hat_openshift_serverless
      solution: "The container images provided by this update can be downloaded from the Red Hat container registry at registry.redhat.io"
      description: "Release 1.35.0 of OpenShift Serverless"
      topic: "Release 1.35.0 of OpenShift Serverless"
      synopsis: "OpenShift Serverless Release 1.35.0"
    mapping:
      components:
        - name: serverless-openshift-kn-operator-135
          repository: registry.stage.redhat.io/openshift-serverless-1/serverless-openshift-kn-rhel8-operator
          pushSourceContainer: true
        - name: serverless-kn-operator-135
          repository: registry.stage.redhat.io/openshift-serverless-1/serverless-kn-operator-rhel8
          pushSourceContainer: true
        - name: serverless-ingress-135
          repository: registry.stage.redhat.io/openshift-serverless-1/serverless-ingress-rhel8
          pushSourceContainer: true
        - name: kn-serving-queue-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-queue-rhel8
          pushSourceContainer: true
        - name: kn-serving-activator-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-activator-rhel8
          pushSourceContainer: true
        - name: kn-serving-autoscaler-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-autoscaler-rhel8
          pushSourceContainer: true
        - name: kn-serving-autoscaler-hpa-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-autoscaler-hpa-rhel8
          pushSourceContainer: true
        - name: kn-serving-controller-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-controller-rhel8
          pushSourceContainer: true
        - name: kn-serving-webhook-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-webhook-rhel8
          pushSourceContainer: true
        - name: kn-serving-storage-version-migration-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-serving-storage-version-migration-rhel8
          pushSourceContainer: true
        - name: net-kourier-kourier-115
          repository: registry.stage.redhat.io/openshift-serverless-1/net-kourier-kourier-rhel8
          pushSourceContainer: true
        - name: net-istio-controller-115
          repository: registry.stage.redhat.io/openshift-serverless-1/net-istio-controller-rhel8
          pushSourceContainer: true
        - name: net-istio-webhook-115
          repository: registry.stage.redhat.io/openshift-serverless-1/net-istio-webhook-rhel8
          pushSourceContainer: true
        - name: kn-eventing-controller-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-controller-rhel8
          pushSourceContainer: true
        - name: kn-eventing-istio-controller-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-istio-controller-rhel8
          pushSourceContainer: true
        - name: kn-eventing-webhook-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-webhook-rhel8
          pushSourceContainer: true
        - name: kn-eventing-migrate-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-migrate-rhel8
          pushSourceContainer: true
        - name: kn-eventing-mtchannel-broker-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-mtchannel-broker-rhel8
          pushSourceContainer: true
        - name: kn-eventing-filter-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-filter-rhel8
          pushSourceContainer: true
        - name: kn-eventing-ingress-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-ingress-rhel8
          pushSourceContainer: true
        - name: kn-eventing-channel-controller-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-channel-controller-rhel8
          pushSourceContainer: true
        - name: kn-eventing-channel-dispatcher-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-channel-dispatcher-rhel8
          pushSourceContainer: true
        - name: kn-eventing-mtping-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-mtping-rhel8
          pushSourceContainer: true
        - name: kn-eventing-apiserver-receive-adapter-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-apiserver-receive-adapter-rhel8
          pushSourceContainer: true
        - name: kn-eventing-jobsink-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-eventing-jobsink-rhel8
          pushSourceContainer: true
        - name: kn-backstage-plugins-eventmesh-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-backstage-plugins-eventmesh-rhel8
          pushSourceContainer: true
        - name: kn-plugin-event-sender-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-plugin-event-sender-rhel8
          pushSourceContainer: true
        - name: kn-client-kn-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-client-kn-rhel8
          pushSourceContainer: true
        - name: kn-plugin-func-func-util-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-plugin-func-func-util-rhel8
          pushSourceContainer: true
        - name: kn-ekb-receiver-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-ekb-receiver-rhel8
          pushSourceContainer: true
        - name: kn-ekb-dispatcher-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-ekb-dispatcher-rhel8
          pushSourceContainer: true
        - name: kn-ekb-kafka-controller-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-ekb-kafka-controller-rhel8
          pushSourceContainer: true
        - name: kn-ekb-webhook-kafka-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-ekb-webhook-kafka-rhel8
          pushSourceContainer: true
        - name: kn-ekb-post-install-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-ekb-post-install-rhel8
          pushSourceContainer: true
        - name: serverless-must-gather-135
          repository: registry.stage.redhat.io/openshift-serverless-1/serverless-must-gather-rhel8
          pushSourceContainer: true
        - name: kn-client-cli-artifacts-115
          repository: registry.stage.redhat.io/openshift-serverless-1/kn-client-cli-artifacts-rhel8
          pushSourceContainer: true
        - name: serverless-bundle-135
          repository: registry.stage.redhat.io/openshift-serverless-1/serverless-operator-bundle
          pushSourceContainer: true
      defaults:
        tags:
          - "{{ git_sha }}"
          - "{{ git_short_sha }}"
          - "1.35.0"
    pyxis:
      secret: pyxis-staging-secret
      server: stage
    sign:
      configMapName: hacbs-signing-pipeline-config-staging-redhatrelease2
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/rh-advisories/rh-advisories.yaml"
    serviceAccountName: release-registry-staging
    timeouts:
      pipeline: "4h0m0s"
