apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../fbc-builder.yaml
patches:
  - path: ../patch_additional_tags.patch.yaml
    target:
      kind: Pipeline
  - path: ../patch_source_image.patch.yaml
    target:
      kind: Pipeline
openapi:
  path: ../pipeline_schema.json
