apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../fbc-builder.yaml
patches:
  - path: ../patch_additional_tags.patch.yaml
    target:
      name: fbc-builder
  - path: ../patch_source_image.patch.yaml
    target:
      name: fbc-builder
  - path: ../patch_snyk_args.patch.yaml
    target:
      name: docker-build
openapi:
  path: ../pipeline_schema.json
