apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-build
spec:
  params:
    - name: skip-fbc-related-image-check
      description: Skip fbc-related-image-check
      type: string
      default: "false"
  tasks:
    - name: fbc-related-image-check
      when:
        - input: $(params.skip-fbc-related-image-check)
          operator: in
          values:
            - "false"
