apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-build
spec:
  params:
    - name: build-args
      description: Array of --build-arg values ("arg=value" strings) for buildah
      type: array
      default: []
  tasks:
    - name: build-container
      params:
        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
