apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../bundle-builder.yaml
patches:
  - path: ../patch_additional_tags.patch.yaml
    target:
      kind: Pipeline
  - path: ../patch_source_image.patch.yaml
    target:
      kind: Pipeline
  - patch: |-
      - op: replace
        path: /metadata/name
        value: bundle-builder
    target:
      kind: Pipeline
openapi:
  path: ../pipeline_schema.json
