apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-java-build
spec:
  tasks:
    - name: build-images-deps
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)
      params:
        - name: IMAGE
          value: $(params.output-image)-deps
        - name: DOCKERFILE
          value: $(params.dockerfile).deps
        - name: CONTEXT
          value: $(params.path-context)
        - name: HERMETIC
          value: "false"
        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
        - name: IMAGE_APPEND_PLATFORM
          value: "true"
      runAfter:
        - prefetch-dependencies
      taskRef:
        name: buildah-remote-oci-ta
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"

    - name: build-image-index-deps
      params:
        - name: IMAGE
          value: $(params.output-image)-deps
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: ALWAYS_BUILD_INDEX
          value: $(params.build-image-index)
        - name: IMAGES
          value:
            - $(tasks.build-images-deps.results.IMAGE_REF[*])
      runAfter:
        - build-images-deps
      taskRef:
        name: build-image-index
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"

    - name: build-images
      params:
        - name: BUILD_ARGS
          value:
            - DEPS_IMAGE=$(tasks.build-image-index-deps.results.IMAGE_URL)@$(tasks.build-image-index-deps.results.IMAGE_DIGEST)
            - $(params.build-args[*])
      runAfter:
        - build-image-index-deps
