apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-java-build
spec:
  tasks:
    - name: build-container-deps
      params:
        - name: IMAGE
          value: $(params.output-image)-deps
        - name: DOCKERFILE
          value: $(params.dockerfile).deps
        - name: CONTEXT
          value: $(params.path-context)
        - name: HERMETIC
          value: "false"
        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)
      runAfter:
        - prefetch-dependencies
      taskRef:
        params:
          - name: name
            value: buildah
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2@sha256:71d3bb81d1c7c9f99946b5f1d4844664f2036636fd114cf5232db644bc088981
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: source
          workspace: workspace
    - name: build-container
      params:
        - name: BUILD_ARGS
          value:
            - DEPS_IMAGE=$(tasks.build-container-deps.results.IMAGE_URL)@$(tasks.build-container-deps.results.IMAGE_DIGEST)
            - $(params.build-args[*])
      runAfter:
        - build-container-deps
