apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: serverless-bundle-135
spec:
  componentName: serverless-bundle-135
  application: serverless-operator-135
   
  build-nudges-ref:
    
    - "serverless-index-135-fbc-413-index"
    
    - "serverless-index-135-fbc-414-index"
    
    - "serverless-index-135-fbc-415-index"
    
    - "serverless-index-135-fbc-416-index"
    
    - "serverless-index-135-fbc-417-index"
    
  
  source:
    git:
      url: https://github.com/openshift-knative/serverless-operator.git
      context: 
      dockerfileUrl: olm-catalog/serverless-operator/Dockerfile
      revision: main
