apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: serverless-index-135
spec:
  componentName: serverless-index-135
  application: serverless-operator-135
   
  source:
    git:
      url: https://github.com/openshift-knative/serverless-operator.git
      context: 
      dockerfileUrl: olm-catalog/serverless-operator-index/Dockerfile
      revision: main
