apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: {{ truncate ( sanitize .ApplicationName ) }}
spec:
  description: {{ .ApplicationName }}
  displayName: {{ .ApplicationName }}
