apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: {{ sanitize .ComponentName }}
spec:
  componentName: {{ .ProjectDirectoryImageBuildStepConfiguration.To }}
  application: {{ truncate ( sanitize .ApplicationName ) }}
  {{ $nudgesN := len .Nudges }} {{ if ne $nudgesN 0 }}
  build-nudges-ref:
    {{ range $nudge := .Nudges }}
    - "{{ $nudge }}"
    {{ end }}
  {{ end }}
  source:
    git:
      url: https://github.com/{{ .ReleaseBuildConfiguration.Metadata.Org }}/{{ .ReleaseBuildConfiguration.Metadata.Repo }}.git
      context: {{ .ProjectDirectoryImageBuildStepConfiguration.ProjectDirectoryImageBuildInputs.ContextDir }}
      dockerfileUrl: {{ .ProjectDirectoryImageBuildStepConfiguration.ProjectDirectoryImageBuildInputs.DockerfilePath }}
      revision: {{ .ReleaseBuildConfiguration.Metadata.Branch }}
