---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    pp.engineering.redhat.com/business-unit: hybrid-platforms
  name: {{{ truncate ( sanitize .Name ) }}}
  namespace: rhtap-releng-tenant
spec:
  applications:
  {{{- range .Applications }}}
    - {{{ truncate ( sanitize . ) }}}
  {{{- end}}}
  origin: ocp-serverless-tenant
  policy: {{{ .Policy }}}
  data:
    releaseNotes:
      product_id: 579
      product_name: "OpenShift Serverless"
      product_version: "{{{ .SOVersion }}}"
      references:
        - https://docs.redhat.com/en/documentation/red_hat_openshift_serverless
      solution: "The container images provided by this update can be downloaded from the Red Hat container registry at registry.redhat.io"
      description: "Release {{{ .SOVersion }}} of OpenShift Serverless"
      topic: "Release {{{ .SOVersion }}} of OpenShift Serverless"
      synopsis: "OpenShift Serverless Release {{{ .SOVersion }}}"
    fbc:
      {{{- if .StagedIndex }}}
      stagedIndex: true
      {{{- end }}}
      fromIndex: "{{{ .FromIndex }}}"
      targetIndex: "{{{ .TargetIndex }}}"
      publishingCredentials: "{{{ .PublishingCredentials }}}"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      allowedPackages: [serverless-operator]
    sign:
      configMapName: {{{ .SignCMName }}}
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/fbc-release/fbc-release.yaml"
    serviceAccountName: {{{ .PipelineSA }}}
    timeouts:
      pipeline: "4h0m0s"
