---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    pp.engineering.redhat.com/business-unit: hybrid-platforms
  name: {{{ truncate ( sanitize .Name ) }}}
  namespace: rhtap-releng-tenant
spec:
  applications:
  {{{- range .Applications }}}
    - {{{ truncate ( sanitize . ) }}}
  {{{- end}}}
  origin: ocp-serverless-tenant
  policy: {{{ .Policy }}}
  data:
    releaseNotes:
      product_id: 579
      product_name: "OpenShift Serverless"
      product_version: "{{{ .SOVersion }}}"
      references:
        - "https://docs.redhat.com/documentation/red_hat_openshift_serverless/"
      type: "RHEA"
      solution: |
        The Red Hat OpenShift Serverless Operator provides a collection of APIs that
        enables containers, microservices and functions to run "serverless".
        Serverless applications can scale up and down (to zero) on demand and be triggered by a
        number of event sources. OpenShift Serverless integrates with a number of
        platform services, such as Monitoring and it is based on the open
        source project Knative.
      description: "The {{{ .SOVersion }}} release of Red Hat OpenShift Serverless Operator."
      topic: |
        The {{{ .SOVersion }}} GA release of Red Hat OpenShift Serverless Operator.
        For more details see [product documentation](https://docs.redhat.com/documentation/red_hat_openshift_serverless).
      synopsis: "Red Hat OpenShift Serverless Release {{{ .SOVersion }}}"
    fbc:
      {{{- if .StagedIndex }}}
      stagedIndex: true
      {{{- end }}}
      fromIndex: "{{{ .FromIndex }}}"
      targetIndex: "{{{ .TargetIndex }}}"
      publishingCredentials: "{{{ .PublishingCredentials }}}"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      allowedPackages: [serverless-operator]
    sign:
      configMapName: {{{ .SignCMName }}}
      cosignSecretName: {{{ .SignSecretName }}}
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/managed/fbc-release/fbc-release.yaml"
    serviceAccountName: {{{ .PipelineSA }}}
    timeouts:
      pipeline: "4h0m0s"
      tasks: "4h0m0s"
