---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/block-releases: "false"
    pp.engineering.redhat.com/business-unit: hybrid-platforms
  name: {{{ truncate ( sanitize .Name ) }}}
  namespace: rhtap-releng-tenant
  annotations:
    rhel_target: el9
spec:
  applications:
  {{{- range .Applications }}}
    - {{{ truncate ( sanitize . ) }}}
  {{{- end}}}
  origin: ocp-serverless-tenant
  policy: {{{ .Policy }}}
  data:
    releaseNotes:
      product_id: [579]
      product_name: "OpenShift Serverless"
      product_version: "fbc"
    fbc:
      {{{- if .StagedIndex }}}
      stagedIndex: true
      {{{- end }}}
      fromIndex: "{{{ .FromIndex }}}"
      targetIndex: "{{{ .TargetIndex }}}"
      publishingCredentials: "{{{ .PublishingCredentials }}}"
      requestTimeoutSeconds: 1500
      buildTimeoutSeconds: 1500
      allowedPackages: [serverless-operator]
    sign:
      configMapName: {{{ .SignCMName }}}
      cosignSecretName: {{{ .SignSecretName }}}
    intention: {{{ .Intention }}}
    enforceContainerFirstSecurityLabels: true
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/managed/fbc-release/fbc-release.yaml"
    serviceAccountName: {{{ .PipelineSA }}}
    timeouts:
      pipeline: "4h0m0s"
      tasks: "4h0m0s"
