---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/block-releases: "false"
    pp.engineering.redhat.com/business-unit: hybrid-platforms
  name: {{{ truncate ( sanitize .Name ) }}}
  namespace: rhtap-releng-tenant
spec:
  applications: [{{{ truncate ( sanitize .ApplicationName ) }}}]
  origin: ocp-serverless-tenant
  policy: {{{ .Policy }}}
  data:
    releaseNotes:
      product_id: [579]
      product_name: "OpenShift Serverless"
      product_version: "{{{ .SOVersion }}}"
    mapping:
      components:
      {{{- range $component := .Components }}}
        - name: {{{ $component.ComponentName }}}
          repositories:
            - url: {{{ $component.ImageRepository }}}
          pushSourceContainer: true
      {{{- end }}}
      defaults:
        tags:
          - "{{ git_sha }}"
          - "{{ git_short_sha }}"
          - "{{{ .SOVersion }}}"
          - "{{{ .SOVersion }}}-{{ timestamp }}"
        pushSourceContainer: true
    pyxis:
      secret: {{{ .PyxisSecret }}}
      server: {{{ .PyxisServer }}}
    intention: {{{ .Intention }}}
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/managed/rh-advisories/rh-advisories.yaml"
    serviceAccountName: {{{ .PipelineSA }}}
    timeouts:
      pipeline: "10h0m0s"
      tasks: "10h0m0s"
