apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: '{{{ .AutoRelease }}}'
    release.appstudio.openshift.io/releasePlanAdmission: '{{{ truncate ( sanitize .ReleasePlanAdmissionName ) }}}'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: {{{ truncate ( sanitize .Name ) }}}
spec:
  application: {{{ truncate ( sanitize .ApplicationName ) }}}
  target: rhtap-releng-tenant
