apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-137-1371-prod
spec:
  snapshot: serverless-operator-137-override-snapshot-5e0a07ed
  releasePlan: serverless-operator-137-1371-prod
  data:
    releaseNotes:
      references:
        - "https://docs.redhat.com/documentation/red_hat_openshift_serverless/"
      type: "RHEA"
