apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-135-fbc-415-1351-prod
spec:
  snapshot: serverless-operator-135-fbc-415-override-snapshot-bd6a1076
  releasePlan: serverless-operator-135-fbc-415-1351-prod
