apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-fbc-418-1360-stage-8
spec:
  snapshot: serverless-operator-136-fbc-418-override-snapshot-05c1eaf0
  releasePlan: serverless-operator-136-fbc-418-1360-stage
