apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-1360-stage-8
spec:
  snapshot: serverless-operator-136-override-snapshot-a4b1920c
  releasePlan: serverless-operator-136-1360-stage
