apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-fbc-416-1360-stage-4
spec:
  snapshot: serverless-operator-136-fbc-416-override-snapshot-6c183d51
  releasePlan: serverless-operator-136-fbc-416-1360-stage
