apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-135-fbc-416-1351-stage
spec:
  snapshot: serverless-operator-135-fbc-416-override-snapshot-4ae880d9
  releasePlan: serverless-operator-135-fbc-416-1351-stage
