apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-1360-stage-2
spec:
  snapshot: serverless-operator-136-override-snapshot-06d899e5
  releasePlan: serverless-operator-136-1360-stage
