apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-fbc-419-1360-stage-2
spec:
  snapshot: serverless-operator-136-fbc-419-override-snapshot-f803b607
  releasePlan: serverless-operator-136-fbc-419-1360-stage
