apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-137-fbc-418-1370-prod
spec:
  snapshot: serverless-operator-137-fbc-418-override-snapshot-e4dd5841
  releasePlan: serverless-operator-137-fbc-418-1370-prod
  data:
    releaseNotes:
      references:
        - "https://docs.redhat.com/documentation/red_hat_openshift_serverless/"
      type: "RHEA"
