apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-1360-stage-12
spec:
  snapshot: serverless-operator-136-override-snapshot-bb5678c8
  releasePlan: serverless-operator-136-1360-stage
