apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-137-fbc-420-1370-stage
spec:
  snapshot: serverless-operator-137-fbc-420-override-snapshot-e89a19c0
  releasePlan: serverless-operator-137-fbc-420-1370-stage
