apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-137-fbc-414-1372-stage
spec:
  snapshot: serverless-operator-137-fbc-414-override-snapshot-be404b0b
  releasePlan: serverless-operator-137-fbc-414-1372-stage
  data:
    releaseNotes:
      references:
        - "https://docs.redhat.com/documentation/red_hat_openshift_serverless/"
      type: "RHEA"
