apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: serverless-operator-136-fbc-416-1361-prod-2
spec:
  snapshot: serverless-operator-136-fbc-416-override-snapshot-9d65467c
  releasePlan: serverless-operator-136-fbc-416-1361-prod
