name: Apply Konflux Override Snapshot
on:
  workflow_dispatch:
    inputs:
      revision:
        description: "SO branch or revision with the manifests"
        default: "main"
        required: true
defaults:
  run:
    shell: bash
jobs:
  snapshot-apply:
    name: Apply Konflux Override Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout serverless operator
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.branch }}"
          repository: 'openshift-knative/serverless-operator'

      - name: Setup kubeconfig
        env:
          KONFLUX_TOKEN: ${{ secrets.KONFLUX_SA_TOKEN }}
        run: |
          kubectl config set-credentials konflux-sa --token "$KONFLUX_TOKEN"
          kubectl config set-cluster konflux --server=https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
          kubectl config set-context konflux-sa@konflux --user=konflux-sa --namespace=ocp-serverless-tenant --cluster=konflux
          kubectl config use-context konflux-sa@konflux

      - name: Apply Override Snapshots
        run: make apply-override-snapshot
